### ISSUE TITLE
[v1.9] Only one numbered backup is created when the name contains non empty, closed brackets or braces.

### ISSUE THREAD

**Issue by ghost** [pstray/rename#3]
The numbered backup doesn't work properly (only one backup is created) when the file or directory name contains non empty, closed brackets or braces. Example:

**Test files:**
```
textfile{0}
tEXTFILE{0}
Textfile{0}
TEXTFILe{0}
TEXTFILE{0}
```
**Command:**

```
rename -bVt 'y/A-Z/a-z/' *
```

**Result:**

```
textfile{0}
textfile{0}.~1~
```

**Expected result:**
```
textfile{0}
textfile{0}.~1~
textfile{0}.~2~
textfile{0}.~3~
textfile{0}.~4~
```

**Comment by pstray** [comment]
Thanks for the bugreport. A new version is uploaded here and on CPAN.

**Comment by ghost** [comment]
> Thanks for the bugreport. A new version is uploaded here and on CPAN.

Awesome. Thank you!
