### ISSUE TITLE
Example in man page gives error

### ISSUE THREAD

**Issue by robin-a-meade** [pstray/rename#4]
This example in the man page hangs waiting for input:

```
rename 's/$/.orig/ */*.[ch]'    # add .orig to source files in */
```

**Comment by robin-a-meade** [comment]
Sorry, it doesn't give that error. It hangs.

**Comment by robin-a-meade** [comment]
Re-opening (closed accidentally)

**Comment by pstray** [comment]
Yes, definitely, that example has the last ' in the wrong place...
